# Molecule managed
#
# This is the dockerfile that will be used to create any of your images.
#
# You can customize it on a per-role or per-scenario basis.

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

# This might be useful if you are finding that some Debian packages, such as tzdata,
# are asking for confirmation when using a noninteractive apt to install them
ENV DEBIAN_FRONTEND=noninteractive

# As you can see this is using tests to figure out the package manager in the
# image in order to install dependencies. Note that debian boxes are installing
# systemd as I often find myself needing it to test some roles.
#
# You can add or remove whatever you need.
RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get install -y python sudo bash ca-certificates iproute2 && apt-get clean; \
    elif [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install python3 sudo python3-devel python*-dnf bash iproute && dnf clean all; \
    elif [ $(command -v yum) ]; then yum makecache fast && yum install -y python sudo yum-plugin-ovl bash iproute && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    elif [ $(command -v zypper) ]; then zypper refresh && zypper install -y python sudo bash python-xml && zypper clean -a; \
    elif [ $(command -v apk) ]; then apk update && apk add --no-cache python sudo bash ca-certificates; \
    elif [ $(command -v xbps-install) ]; then xbps-install -Syu && xbps-install -y python sudo bash ca-certificates && xbps-remove -O; fi
