---

dependency:
  name: 'galaxy'

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8

driver:
  name: docker

provisioner:
  name: ansible
  options:
    vv: true
  log: true

platforms:
  - name: centos_8
    image: centos:8
  - name: centos_7
    image: centos:7
  - name: centos_6
    image: centos:6

verifier:
  name: testinfra
